// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzgkozweshaucfbfdorz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6Z2tvendlc2hhdWNmYmZkb3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NDcwMDksImV4cCI6MjA2NTQyMzAwOX0.2pKwUFK4tPMH14l-s0TcEZ0m9uQC8hlPUSxS83FvMXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);